<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AHLPT2208063-N" failures="0" tests="2" name="test_case.Login" time="4.025" errors="1" timestamp="2025-09-15T19:10:48 IST" skipped="1">
  <testcase classname="test_case.Login" name="Login_Data" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[Test Case Started : logoutMainUser]]>
    </system-out>
  </testcase> <!-- Login_Data -->
  <testcase classname="test_case.Login" name="Launch_Browser" time="4.024">
    <error message="D:\Backup\Projects\rhb.comsrc\test\resources\Utilites\Test_Data.properties (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: D:\Backup\Projects\rhb.comsrc\test\resources\Utilites\Test_Data.properties (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at base.Base_Class.Launch_Browser(Base_Class.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:655)
at org.testng.TestRunner.beforeRun(TestRunner.java:644)
at org.testng.TestRunner.run(TestRunner.java:610)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Launch_Browser -->
  <system-out>
    <![CDATA[Test Case Started : Login_Data
Test Case Started : logoutMainUser
Test Case Started : Login_Test
Test Case Started : Login_Test
Test Case Started : Login_Test
Test Case Started : Login_Test
Test Case Started : Block_User
Test Case Started : Block_User
Test Case Started : Block_User
Test Case Started : Block_User
Test Case Started : Block_User
Test Case Started : Block_User
Test Case Started : MainUserLogin
Test Case Started : Add_Group
Test Case Started : Add_Role
==============================================================================================
Total Passed: 0(+0), Failures: 0(+0), Skips: 15(+15)
==============================================================================================]]>
  </system-out>
</testsuite> <!-- test_case.Login -->
